import { Product, TeamMember, Customer } from "./types";

export const COMPANY_INFO = {
  address:
    "CIA Office Complex, Main Road, Sector - III, I.D.A Phase-II, Near Prof. Jaya Sankar Circle, Cherlapally, R.R.District, Secunderabad, Telangana 500051",
  phone: "+91-94414 02957",
  email: "info@ryltenergy.com",
  tagline: "Redefine Your Life With Technology",
  vision:
    "To be a pioneer in sustainable and innovative heating solutions, transforming every space into a comfortable and energy-efficient environment.",
  mission:
    "To design and deliver advanced HVAC-based heating solutions that combine reliability, efficiency, and innovation, reducing energy consumption while enhancing comfort.",
};

// Updated images to be more relevant/fresh
export const PRODUCTS: Product[] = [
  {
    id: "pool-heat-pump",
    title: "Swimming Pool Heat Pump",
    category: "Heating",
    description:
      "Advanced air-source refrigeration cycle technology designed to deliver efficient and eco-friendly pool heating. Saves up to 70% energy compared to traditional electric or gas heaters.",
    image: "/images/pool-heat-pump.png",
    brochure: {
      url: "/brochures/Swimming Pool Heat Pump.pdf",
      filename: "Swimming Pool Heat Pump.pdf",
    },
    features: [
      "Titanium Tube Heat Exchanger (Corrosion Resistant)",
      "Smart Wi-Fi Controller",
      "Works in all Indian Climates (Hot, Humid, Cold)",
      "Low Noise Operation",
      "R410A/R32 Eco-friendly Refrigerant",
    ],
    applications: [
      "Residential Swimming Pools",
      "Hotels & Resorts",
      "Sports Clubs & Gyms",
      "Indoor Pools",
    ],
    models: [
      {
        name: "27kW",
        specs: [
          { label: "Rated Input Power", value: "3.9 kW" },
          { label: "Power Supply", value: "415/3/50 V/Ph/Hz" },
          { label: "COP", value: "6.3 w/w" },
          { label: "Compressor Type", value: "Scroll" },
          { label: "Number of Compressors", value: "01" },
          { label: "Number of Fans", value: "01" },
          { label: "Total Input Power to Fan", value: "180 W" },
          { label: "Heat Exchanger", value: "Titanium Tube Heat Exchanger" },
          { label: "Refrigerant", value: "R407C/R410A/R32" },
          { label: "Noise", value: "55 dB(A)" },
          { label: "Water Flow Volume", value: "12 m³/h" },
          { label: "Unit Size", value: "1000 x 700 x 700 mm" },
          { label: "Net Weight", value: "140 kg" },
        ],
      },
      {
        name: "40kW",
        specs: [
          { label: "Rated Input Power", value: "7.8 kW" },
          { label: "Power Supply", value: "415/3/50 V/Ph/Hz" },
          { label: "COP", value: "5.1 w/w" },
          { label: "Compressor Type", value: "Scroll" },
          { label: "Number of Compressors", value: "01" },
          { label: "Number of Fans", value: "01" },
          { label: "Total Input Power to Fan", value: "600 W" },
          { label: "Heat Exchanger", value: "Titanium Tube Heat Exchanger" },
          { label: "Refrigerant", value: "R407C/R410A/R32" },
          { label: "Noise", value: "58 dB(A)" },
          { label: "Water Flow Volume", value: "20 m³/h" },
          { label: "Unit Size", value: "1000 x 700 x 700 mm" },
          { label: "Net Weight", value: "160 kg" },
        ],
      },
      {
        name: "55kW",
        specs: [
          { label: "Rated Input Power", value: "8.1 kW" },
          { label: "Power Supply", value: "415/3/50 V/Ph/Hz" },
          { label: "COP", value: "6.1 w/w" },
          { label: "Compressor Type", value: "Scroll" },
          { label: "Number of Compressors", value: "02" },
          { label: "Number of Fans", value: "02" },
          { label: "Total Input Power to Fan", value: "380 W" },
          { label: "Heat Exchanger", value: "Titanium Tube Heat Exchanger" },
          { label: "Refrigerant", value: "R407C/R410A/R32" },
          { label: "Noise", value: "66 dB(A)" },
          { label: "Water Flow Volume", value: "12 m³/h" },
          { label: "Unit Size", value: "1000 x 1000 x 700 mm" },
          { label: "Net Weight", value: "280 kg" },
        ],
      },
      {
        name: "80kW",
        specs: [
          { label: "Rated Input Power", value: "15.5 kW" },
          { label: "Power Supply", value: "415/3/50 V/Ph/Hz" },
          { label: "COP", value: "5.1 w/w" },
          { label: "Compressor Type", value: "Scroll" },
          { label: "Number of Compressors", value: "02" },
          { label: "Number of Fans", value: "02" },
          { label: "Total Input Power to Fan", value: "1220 W" },
          { label: "Heat Exchanger", value: "Titanium Tube Heat Exchanger" },
          { label: "Refrigerant", value: "R407C/R410A/R32" },
          { label: "Noise", value: "68 dB(A)" },
          { label: "Water Flow Volume", value: "20 m³/h" },
          { label: "Unit Size", value: "1000 x 1000 x 700 mm" },
          { label: "Net Weight", value: "300 kg" },
        ],
      },
    ],
  },
  {
    id: "industrial-dehumidifier",
    title: "Industrial Dehumidifier (Food & Pharma)",
    category: "Dehumidification",
    description:
      "Specialized dehumidifiers designed for the food and confectionery industry. Prevents moisture damage, stickiness, and sugar bloom in chocolates and candies.",
    image: "/images/industrial-dehumidifier.png",
    brochure: {
      url: "/brochures/Industrial Dehumidifier.pdf",
      filename: "Industrial Dehumidifier.pdf",
    },
    features: [
      "Prevents Sugar/Fat Bloom",
      "Food-Safe Materials",
      "High Capacity Moisture Removal",
      "Energy Efficient Scroll Compressors",
      "Precise Humidity Control",
    ],
    applications: [
      "Chocolate Factories",
      "Candy & Gems Production",
      "Food Packaging Areas",
      "Warehouses & Cold Storage",
      "Pharmaceutical Units",
    ],
    models: [
      {
        name: "DR450",
        specs: [
          { label: "Dehumidification @ 30°C - 80% RH", value: "437 L/24h" },
          { label: "Dehumidification @ 20°C - 60% RH", value: "203 L/24h" },
          { label: "Air Circulation", value: "3000 m³/h" },
          { label: "Number of Compressors", value: "01" },
          { label: "Type of Compressor", value: "Scroll" },
          { label: "Number of Fans", value: "01" },
          { label: "Type of Fan", value: "Axial" },
          { label: "Nominal Power Consumption", value: "4.9 kW" },
          { label: "Maximum Current Consumption", value: "9 A" },
          { label: "Operating Range - Humidity", value: "40-99% RH" },
          { label: "Operating Range - Temperature", value: "15-36°C" },
          { label: "Voltage Supply", value: "400/3/50 V/Ph/Hz" },
          { label: "Sound Pressure Level", value: "63 dB(A)" },
          { label: "Refrigerant", value: "R410A/R407c/R134a" },
          { label: "Dimensions (H x W x D)", value: "1000 x 700 x 700 mm" },
          { label: "Weight", value: "148 kg" },
        ],
      },
      {
        name: "DR700",
        specs: [
          { label: "Dehumidification @ 30°C - 80% RH", value: "692 L/24h" },
          { label: "Dehumidification @ 20°C - 60% RH", value: "352 L/24h" },
          { label: "Air Circulation", value: "3500 m³/h" },
          { label: "Number of Compressors", value: "01" },
          { label: "Type of Compressor", value: "Scroll" },
          { label: "Number of Fans", value: "01" },
          { label: "Type of Fan", value: "Axial" },
          { label: "Nominal Power Consumption", value: "7.16 kW" },
          { label: "Maximum Current Consumption", value: "14.3 A" },
          { label: "Operating Range - Humidity", value: "40-99% RH" },
          { label: "Operating Range - Temperature", value: "15-36°C" },
          { label: "Voltage Supply", value: "400/3/50 V/Ph/Hz" },
          { label: "Sound Pressure Level", value: "65 dB(A)" },
          { label: "Refrigerant", value: "R410A/R407c/R134a" },
          { label: "Dimensions (H x W x D)", value: "1000 x 1200 x 700 mm" },
          { label: "Weight", value: "230 kg" },
        ],
      },
      {
        name: "DR900",
        specs: [
          { label: "Dehumidification @ 30°C - 80% RH", value: "874 L/24h" },
          { label: "Dehumidification @ 20°C - 60% RH", value: "406 L/24h" },
          { label: "Air Circulation", value: "6000 m³/h" },
          { label: "Number of Compressors", value: "02" },
          { label: "Type of Compressor", value: "Scroll" },
          { label: "Number of Fans", value: "02" },
          { label: "Type of Fan", value: "Axial" },
          { label: "Nominal Power Consumption", value: "9.8 kW" },
          { label: "Maximum Current Consumption", value: "18 A" },
          { label: "Operating Range - Humidity", value: "40-99% RH" },
          { label: "Operating Range - Temperature", value: "15-36°C" },
          { label: "Voltage Supply", value: "400/3/50 V/Ph/Hz" },
          { label: "Sound Pressure Level", value: "63 dB(A)" },
          { label: "Refrigerant", value: "R410A/R407c/R134a" },
          { label: "Dimensions (H x W x D)", value: "1000 x 1200 x 700 mm" },
          { label: "Weight", value: "290 kg" },
        ],
      },
      {
        name: "DR1150",
        specs: [
          { label: "Dehumidification @ 30°C - 80% RH", value: "1129 L/24h" },
          { label: "Dehumidification @ 20°C - 60% RH", value: "609 L/24h" },
          { label: "Air Circulation", value: "6500 m³/h" },
          { label: "Number of Compressors", value: "02" },
          { label: "Type of Compressor", value: "Scroll" },
          { label: "Number of Fans", value: "02" },
          { label: "Type of Fan", value: "Axial" },
          { label: "Nominal Power Consumption", value: "12.06 kW" },
          { label: "Maximum Current Consumption", value: "23.3 A" },
          { label: "Operating Range - Humidity", value: "40-99% RH" },
          { label: "Operating Range - Temperature", value: "15-36°C" },
          { label: "Voltage Supply", value: "400/3/50 V/Ph/Hz" },
          { label: "Sound Pressure Level", value: "65 dB(A)" },
          { label: "Refrigerant", value: "R410A/R407c/R134a" },
          { label: "Dimensions (H x W x D)", value: "1000 x 1600 x 700 mm" },
          { label: "Weight", value: "290 kg" },
        ],
      },
    ],
  },
  {
    id: 'commercial-heat-pump',
    title: 'Commercial Heat Pump',
    category: 'Heating',
    description:
      'Energy-efficient commercial heat pump water heating system designed for hostels, hospitals, lodges, restaurants and spa facilities. Operates in ambient temperatures from 15°C to 55°C with maximum water temperature up to 75°C and delivers high COP up to 5.0 for maximum savings.',
    image: '/images/commercial-heat-pump.png',
    brochure: {
      url: "/brochures/Commercial Heat Pump.pdf",
      filename: "Commercial Heat Pump.pdf",
    },
    features: [
      'Save up to 60% on hot water bills',
      'High COP up to 5.0',
      'Maximum water temperature up to 75°C',
      'Ambient operating temperature: 15°C to 55°C',
      'Scroll/Copeland/Danfoss compressor',
      'Co-axial tube-in-tube heat exchanger',
      'Eco-friendly refrigerants (R407C / R404A / R134a)',
      '415V / 3 Phase / 50Hz power supply',
      'Available in 600, 1000, and 1200 L/Hr capacities',
    ],
    applications: [
      'Hostels',
      'Hospitals',
      'Lodges',
      'Restaurants',
      'Spa',
      'Commercial Buildings',
    ],
    models: [
      {
        name: 'RHP-600',
        specs: [
          { label: 'Water Output', value: '600 L/Hr' },
          { label: 'Max Water Temperature', value: '60°C' },
          { label: 'Rated Input Power', value: '5.6 kW' },
          { label: 'Rated Heat Output', value: '24.5 kW' },
          { label: 'Power Supply', value: '415V / 3 Phase / 50Hz' },
          { label: 'COP', value: '4.3' },
          { label: 'Compressor Type', value: 'Scroll / Copeland / Danfoss' },
          { label: 'Number of Compressors', value: '1' },
          { label: 'Total Input Power to Fan', value: '180 W' },
          { label: 'Heat Exchanger', value: 'Co-axial Tube in Tube Heat Exchanger' },
          { label: 'Refrigerant', value: 'R407C / R404A / R134a' },
          { label: 'Unit Size', value: '1000 x 700 x 700 mm' },
          { label: 'Net Weight', value: '140 kg' },
        ],
      },
      {
        name: 'RHP-1000',
        specs: [
          { label: 'Water Output', value: '1000 L/Hr' },
          { label: 'Max Water Temperature', value: '60°C' },
          { label: 'Rated Input Power', value: '8 kW' },
          { label: 'Rated Heat Output', value: '42 kW' },
          { label: 'Power Supply', value: '415V / 3 Phase / 50Hz' },
          { label: 'COP', value: '5.0' },
          { label: 'Compressor Type', value: 'Scroll / Copeland / Danfoss' },
          { label: 'Number of Compressors', value: '1' },
          { label: 'Total Input Power to Fan', value: '250 W' },
          { label: 'Heat Exchanger', value: 'Co-axial Tube in Tube Heat Exchanger' },
          { label: 'Refrigerant', value: 'R407C / R404A / R134a' },
          { label: 'Unit Size', value: '1000 x 700 x 700 mm' },
          { label: 'Net Weight', value: '160 kg' },
        ],
      },
      {
        name: 'RHP-1200',
        specs: [
          { label: 'Water Output', value: '1200 L/Hr' },
          { label: 'Max Water Temperature', value: '60°C' },
          { label: 'Rated Input Power', value: '11.6 kW' },
          { label: 'Rated Heat Output', value: '49 kW' },
          { label: 'Power Supply', value: '415V / 3 Phase / 50Hz' },
          { label: 'COP', value: '4.2' },
          { label: 'Compressor Type', value: 'Scroll / Copeland / Danfoss' },
          { label: 'Number of Compressors', value: '2' },
          { label: 'Total Input Power to Fan', value: '360 W' },
          { label: 'Heat Exchanger', value: 'Co-axial Tube in Tube Heat Exchanger' },
          { label: 'Refrigerant', value: 'R407C / R404A / R134a' },
          { label: 'Unit Size', value: '1000 x 1000 x 700 mm' },
          { label: 'Net Weight', value: '250 kg' },
        ],
      },
      {
        name: 'RHP-1000 (High Temp 75°C)',
        specs: [
          { label: 'Water Output', value: '1000 L/Hr' },
          { label: 'Max Water Temperature', value: '75°C' },
          { label: 'Rated Input Power', value: '9 kW' },
          { label: 'Rated Heat Output', value: '42 kW' },
          { label: 'Power Supply', value: '415V / 3 Phase / 50Hz' },
          { label: 'COP', value: '4.8' },
          { label: 'Compressor Type', value: 'Scroll / Copeland / Danfoss' },
          { label: 'Number of Compressors', value: '2' },
          { label: 'Total Input Power to Fan', value: '360 W' },
          { label: 'Heat Exchanger', value: 'Co-axial Tube in Tube Heat Exchanger' },
          { label: 'Refrigerant', value: 'R407C / R404A / R134a' },
          { label: 'Unit Size', value: '1000 x 1000 x 700 mm' },
          { label: 'Net Weight', value: '200 kg' },
        ],
      },
    ],
  },
  // {
  //   id: 'advanced-dehumidifier',
  //   title: 'Advanced Dehumidification Solution (RYLT-80)',
  //   category: 'Dehumidification',
  //   description: 'High-performance drying solution designed for demanding industrial applications requiring specific temperature and humidity maintenance (35°C & 36% RH).',
  //   image: 'https://picsum.photos/id/60/800/600', // Tech/Office/Clean vibe
  //   features: [
  //     'Removes 82kg water/12h (Single Unit)',
  //     'Wi-Fi Enabled Monitoring',
  //     'Automatic Defrost & Memory Restart',
  //     'Portable Roto-molded Housing',
  //     '12 Months Warranty'
  //   ],
  //   applications: [
  //     'Industrial Drying Processes',
  //     'Paper/Sheet Drying',
  //     'Sensitive Material Storage'
  //   ],
  //   models: [
  //     {
  //       name: 'RYLT-80',
  //       specs: [
  //         { label: 'Capacity', value: '7 L/H' },
  //         { label: 'Power Input', value: '5 kW' },
  //         { label: 'COP', value: 'Up to 4.0' },
  //         { label: 'Dimensions', value: '900 x 700 x 900 mm' }
  //       ]
  //     },
  //     {
  //       name: 'RYLT-240',
  //       specs: [
  //         { label: 'Capacity', value: '22 L/H' },
  //         { label: 'Warranty', value: '12 Months' },
  //         { label: 'Control', value: 'Wi-Fi Smart Control' },
  //       ]
  //     }
  //   ]
  // }
];

export const TEAM: TeamMember[] = [
  {
    id: 1,
    name: "Engineering Lead",
    role: "Head of R&D",
    bio: "Expert in thermodynamic systems with 15+ years in HVAC innovation.",
    image: "/images/Engineering Lead.png",
  },
  {
    id: 2,
    name: "Operations Manager",
    role: "Production Head",
    bio: "Ensures global quality standards and 'Make in India' excellence.",
    image: "/images/Operations Manager.png",
  },
  {
    id: 3,
    name: "Sales Director",
    role: "Customer Success",
    bio: "Dedicated to providing tailored energy solutions for industrial clients.",
    image: "/images/Sales Director.png",
  },
];

export const CUSTOMERS: Customer[] = [
  { id: 1, name: "Major Hotel Chains", logo: "Hotel Partners" },
  { id: 2, name: "Pharmaceutical Giants", logo: "Pharma Corp" },
  { id: 3, name: "Food Processing Units", logo: "Food Industries" },
  { id: 4, name: "Sports Complexes", logo: "Sports Authority" },
  { id: 5, name: "Swimming Pool Operators", logo: "Swimming Pool" },
];

export const GALLERY_ITEMS = [
  {
    id: 1,
    category: "Heating",
    type: "image",
    src: "/images/gallery-img1.png",
    title: "Pool Heating Installation",
    description: "Installation of a high-efficiency pool heat pump for year-round comfort.",
  },
  {
    id: 2,
    category: "Heating",
    type: "image",
    src: "/images/gallery-img2.png",
    title: "Resort Swimming Pool",
    description: "Luxury resort pool solution optimized for energy savings and comfort.",
  },
  {
    id: 3,
    category: "Dehumidification",
    type: "image",
    src: "/images/gallery-img3.png",
    title: "Industrial Facility",
    description: "Climate control installation tailored for demanding industrial environments.",
  },
  {
    id: 4,
    category: "Dehumidification",
    type: "image",
    src: "/images/gallery-img4.png",
    title: "Office Ventilation",
    description: "Workplace humidity control project for a modern office space.",
  },
  {
    id: 5,
    category: "Dehumidification",
    type: "image",
    src: "/images/gallery-img5.png",
    title: "Product Storage",
    description: "Protected storage environment for sensitive goods and materials.",
  },
  {
    id: 6,
    category: "Heating",
    type: "image",
    src: "/images/gallery-img6.png",
    title: "Hotel Rooftop Pool",
    description: "Rooftop pool heating installation for a high-end hospitality property.",
  },
  {
    id: 7,
    category: "Others",
    type: "image",
    src: "/images/others-img1.png",
    title: "Solar Pool Setup",
    description: "Hybrid solar-assisted pool heating visualization for eco-conscious sites.",
  },
  {
    id: 8,
    category: "Others",
    type: "image",
    src: "/images/others-img2.png",
    title: "Warehouse Comfort",
    description: "Low-energy humidity control concept for commercial storage spaces.",
  },
  {
    id: 9,
    category: "Others",
    type: "image",
    src: "/images/others-img3.png",
    title: "Corporate Wellness",
    description: "Heat pump solution for office wellness centers and recreational pools.",
  },
  {
    id: 10,
    category: "Others",
    type: "image",
    src: "/images/others-img4.png",
    title: "Gym Pool Upgrade",
    description: "Energy-smart heating system for fitness center swimming pools.",
  },
  {
    id: 11,
    category: "Others",
    type: "video",
    src: "/images/others-video1.png",
    title: "Video: Heat Pump Showcase",
    description: "Short overview of our heat pump installation process.",
  },
  {
    id: 12,
    category: "Others",
    type: "video",
    src: "/images/others-video2.png",
    title: "Video: Dehumidifier Demo",
    description: "Product demo of our industrial dehumidifier system.",
  },
  {
    id: 13,
    category: "Others",
    type: "video",
    src: "/images/others-video3.png",
    title: "Video: Resort Case Study",
    description: "Customer case study covering a resort pool heat pump project.",
  },
  {
    id: 14,
    category: "Others",
    type: "video",
    src: "/images/others-video4.png",
    title: "Video: Warehouse Climate Control",
    description: "Visual story of our warehouse humidity management installation.",
  },
];
